#ifndef __LOLIROFLE_IRCBOT_API_COMMANDPARAMETER_H_INCLUDED__
#define __LOLIROFLE_IRCBOT_API_COMMANDPARAMETER_H_INCLUDED__

#include <lolie/Stringp.h>

enum CommandParameterType{
	COMMAND_PARAMETER_TYPE_NONE,
	COMMAND_PARAMETER_TYPE_SEPARATED,
	COMMAND_PARAMETER_TYPE_FREE,
	COMMAND_PARAMETER_TYPE_CUSTOMPARSER
};

enum CommandParameterValueType{
	COMMAND_PARAMETER_VALUE_TYPE_INTEGER,
	COMMAND_PARAMETER_VALUE_TYPE_STRING,
	COMMAND_PARAMETER_VALUE_TYPE_FLOATINGPOINT,
	COMMAND_PARAMETER_VALUE_TYPE_CHARACTER
};

enum CommandParameterValueRequirement{
	COMMAND_PARAMETER_VALUE_REQUIRED,
	COMMAND_PARAMETER_VALUE_OPTIONAL,
	COMMAND_PARAMETER_VALUE_VARARG
};

struct CommandParameterValue{
	Stringp name;
	enum CommandParameterValueType type;
	enum CommandParameterValueRequirement requirement;
};

#endif
